### ISSUE TITLE
publicProfileGetPersonalInfo

### ISSUE THREAD

**Issue by bgenia** [s21toolkit/s21schema#2]
Опишите какие запросы перестали работать, можете приложить примеры ответов

publicProfileGetPersonalInfo

**Comment by Yury03** [comment]
Старый запрос выдает ошибку. Изменилась структура ответа и сам запрос. Прикладываю исправленный файл, для замены в библиотеке на Go s21client.
[public_profile_get_personal_info.go.zip](https://github.com/s21toolkit/s21schema/files/14484755/public_profile_get_personal_info.go.zip)

**Comment by EnergoStalin** [comment]
После их последнего глобального обновления с графом схема ещё обновлена не была т.к. мы начали переходить на новый способ её генерации с помощью модифицированного дефолтного introspection query который фильтр пропускает. Наработки [здесь](https://github.com/s21toolkit/s21introspector). На сколько я помню осталось только в s21auto геренацию из gql прикрутить.

**Comment by bgenia** [comment]
Больше не имеет смысла, закрыто
